[project]
name = "clip-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.1",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pytest>=8.4.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
